name: Sync Docu to Wiki

on:
  push:
    paths:
      - 'docs/de/sprinklecontrol.md'
      - 'docs/de/img/*'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone wiki repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git ./wiki

      - name: Copy Docu to Wiki
        run: |
          cp docs/de/sprinklecontrol.md ./wiki/Sprinklecontrol-Wiki-Deutsch.md
          cp docs/de/img/* ./wiki/img/

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd wiki
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "Sync Docu to Wiki"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
          fi
